### ISSUE TITLE
Single topic vs multitopic

### ISSUE THREAD

**Issue by rzr** [AnaviTechnology/anavi-gas-detector-sw#1]
I thought it would be less consuming to use a single mqtt publish with a collection of (updated) fields, than multiple mqtt actions.

Any opinion on this ?

**Comment by leon-anavi** [comment]
Hi @rzr,

Seems there are no complains with the current implementation based on the Home Assistant conventions for MQTT components. This is the core of the whole default firmware therefore I will close this issue.

Thanks,
Leon
