### ISSUE TITLE
How to get CO2 values (PPM) from MQ-135?

### ISSUE THREAD

**Issue by craftzdog** [AnaviTechnology/anavi-gas-detector-sw#2]
Hi, I'm considering to buy it and I'd like to visualize PPM level.
I read the source code but I could find only the lines for detecting Gas level.
Thanks!

**Comment by leon-anavi** [comment]
Hi @craftzdog,

MQ-135 gas sensor is a low-cost air quality sensor with a wide detecting scope of various dangerous gases. However it isn't capable and accurate enough to provide PPM per specific component of the air. For more information have a look at the datasheet and this video about MQ-135: https://www.youtube.com/watch?v=Ku4Y29XPyyo

If you need  PPM of eCO2 (equivalent calculated carbon-dioxide) you better have a look at CCS811 air quality sensor. It is available as I2C sensor breakout boards so with male to female jumper wires you can physically attach it to any of the 3 slots of ANAVI Gas Detector (actually there are 4 I2C slots available on ANAVI Gas Detector, the 4th is dedicated for a mini OLED display). As of the moment the default open source firmware of ANAVI Gas Detector doesn't support CCS811 but support can be implemented in a similar way as for other I2C sensor modules,[ for example HTU21D](https://github.com/AnaviTechnology/anavi-gas-detector-sw/blob/master/anavi-gas-detector-sw/anavi-gas-detector-sw.ino#L996). ANAVI Gas Detector is entirely open source project and this or other improvements are always welcome.

I hope this information provides enough details. I will close the issue. Please re-opened it if you have any follow-up questions.

Thank you for interest and support for open source projects like ANAVI Gas Detector :)

Thanks,
Leon

**Comment by zachfi** [comment]
I got a 10 pack of MQ gas sensors on amazon for around $15 US.  I think they should be supported, but I haven't tested them all.

**Comment by leon-anavi** [comment]
Hi @xaque208,

Most probably if they are MQ-135 gas sensors they should be fine. Just check that the pins on the sensors matches the pins on the dedicated connector on the board. ANAVI Gas Detector provides 5V to the connector for MQ sensor, so other MQ sensors operating at 5V are supported.

Best regards,
Leon

**Comment by craftzdog** [comment]
Thank you for clarifying! I'll consider other options :)
